# Generated by Django 4.2.11 on 2026-07-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_proyecto_id_tareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('completado', 'Completado')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
