# Generated by Django 4.2.11 on 2026-07-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_proyecto_estado_proyecto_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('terminada', 'Terminada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='tareas',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20),
        ),
    ]
