# Generated by Django 4.2.11 on 2026-07-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_proyecto_creado_por_tareas_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='en_papelera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tareas',
            name='en_papelera',
            field=models.BooleanField(default=False),
        ),
    ]
